### PR TITLE
Prettier e slint

### LINKED ISSUE #8: Initial Setup
# User story 
As a developer I want to setup the basic template

## Acceptance criteria

- [x] Prettier
- [x] Eslint
- [x] Create-React-App
- [x] Storybook
- [x] Json-Server

### PR DESCRIPTION
**Pull request by mskradde**

### CODE REVIEW

**Review by manuelpapa — APPROVED** [review]
GJ!

**Comment by DrBennemin** [comment]
superb!

**Review by manuelsanchez2 — APPROVED** [review]
incredible job mate!

**Review by manuelsanchez2 — APPROVED** [review]
gj!

**Review by manuelpapa — APPROVED** [review]

**Pull request merged**
